name: "Check Links in docs"
on:
  pull_request:
    types: [opened]
  pull_request_review:
    types: [submitted]

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      actions: write
      pull-requests: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          args: --max-concurrency 30 --exclude-all-private --verbose --no-progress './**/*.md' './**/*.html'
          fail: false
          jobSummary: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: |
            report
            automated issue
